Fix DoS #183
gobby/gobby pull request #184
Opened 2020-10-05 00:48 UTC by junorouse

Print warning message when language is a NULL pointer.

2020-10-05 06:19 UTC, aburgm requested changes
If you are concerned about this, you might also want to consider handling the case of language_id being empty, which would probably lead to the same segmentation fault?

2020-10-05 06:19 UTC, aburgm commented on code/commands/view-commands.cpp
> +		if(language != NULL) {
This should be `language == NULL` or you are doing the exact opposite of your intention :)

2020-10-06 01:16 UTC, iamahuman commented on code/commands/view-commands.cpp
> +			return;
Are you sure you want to return from the function here? `NULL` is a perfectly legal value for `language` in this case, as can be seen by the initial value of `language` which will be used as-is when the `language_id.empty()` condition above is false.

Perhaps simply taking out `g_assert(language != NULL);` would suffice, and the user is not going to look at the GLib warning logs anyway.

2020-10-06 06:42 UTC, aburgm commented
I'm sorry, I just had another look at #183, and I don't believe this is a correct fix for the issue. Looking at the location of the crash (from #183), we got:

```
Thread 1 "gobby-0.5" received signal SIGSEGV, Segmentation fault.
0x000055555561d681 in Gobby::TextSessionView::set_language (this=0x0, language=language@entry=0x0) at code/core/textsessionview.cpp:429
429		gtk_source_buffer_set_language(m_buffer, language);
```

I don't think the problem is that language is NULL, but that `this` is NULL. In other words, when you make your dbus call with an existing language ID, I would still expect the application to crash, and it is the `g_assert(m_current_view != NULL)` that needs to be protected with a proper guard, not the language. A NULL language is actually valid, it just disables syntax highlighting altogether (see [docs](https://developer.gnome.org/gtksourceview/stable/GtkSourceBuffer.html#gtk-source-buffer-set-language)).

I'm not sure why `m_current_view` would be NULL; are you maybe making the call when there is no document open in Gobby? I think the menu item is greyed out in this case, but maybe the d-bus call can still be made. In that case I would expect many other "invalid" menu actions could be triggered that way as well, leading to similar problems.

2020-10-06 09:17 UTC, junorouse commented
@aburgm Sorry, I mislead the root cause of this crash.

> are you maybe making the call when there is no document open in Gobby?
- Yes.

> In that case I would expect many other "invalid" menu actions could be triggered that way as well, leading to similar problems.

So the proper solutions might be ...

1.  Patch all the `g_assert` codes to print warning message instead of crashing.

```
juno@ubuntu:~/Desktop/gobby$ grep -R 'g_assert(m_current_view != NULL);' .
./code/commands/view-commands.cpp:	g_assert(m_current_view != NULL);
./code/commands/edit-commands.cpp:	g_assert(m_current_view != NULL);
./code/commands/edit-commands.cpp:	g_assert(m_current_view != NULL);
./code/commands/edit-commands.cpp:	g_assert(m_current_view != NULL);
./code/commands/edit-commands.cpp:	g_assert(m_current_view != NULL);
./code/commands/edit-commands.cpp:	g_assert(m_current_view != NULL);
./code/commands/edit-commands.cpp:	g_assert(m_current_view != NULL);
./code/commands/edit-commands.cpp:	g_assert(m_current_view != NULL);
./code/commands/edit-commands.cpp:	g_assert(m_current_view != NULL);
./code/commands/edit-commands.cpp:	g_assert(m_current_view != NULL);
./code/commands/edit-commands.cpp:	g_assert(m_current_view != NULL);
./code/dialogs/goto-dialog.cpp:		g_assert(m_current_view != NULL);
./code/dialogs/goto-dialog.cpp:	g_assert(m_current_view != NULL);
```

2. to do nothing and maintain the current logic. (won't fix)

2020-10-08 06:31 UTC, aburgm commented
> Patch all the g_assert codes to print warning message instead of crashing.

This would be fine with me.

> to do nothing and maintain the current logic. (won't fix)

But this too. :)

2020-10-19 01:17 UTC, junorouse commented
@aburgm I made a patch with the former one.

2020-12-02 09:27 UTC, junorouse commented
@aburgm ping!

2020-12-02 22:17 UTC, merged

2020-12-02 22:17 UTC, aburgm commented
Looks good to me, sorry for the delay!

2020-12-26 07:39 UTC, carnil commented
Looks this got [CVE-2020-35450](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-35450) assigned.

2020-12-28 08:47 UTC, abergmann commented
[CVE-2020-35450](https://nvd.nist.gov/vuln/detail/CVE-2020-35450) was assigned to this issue.